// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VanButton: typeof import('vant/es')['Button'];
    VanConfigProvider: typeof import('vant/es')['ConfigProvider'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanLoading: typeof import('vant/es')['Loading'];
    VanPopup: typeof import('vant/es')['Popup'];
    VanSticky: typeof import('vant/es')['Sticky'];
    VanSwipe: typeof import('vant/es')['Swipe'];
    VanSwipeItem: typeof import('vant/es')['SwipeItem'];
    VarButton: typeof import('@varlet/ui')['_ButtonComponent'];
  }
}

export {};
